name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  sqlite3: ^2.7.4
  dotenv: ^4.2.0
  get_it: ^8.0.3
  logger: ^2.5.0
  csv: ^6.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
